# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJ1FeX7PcnoFVOJwjwp3_0i4LAvlUpob
"""

str = 'jhguysdtfsjkbjkf'
T=("hshguysdg", "jhgjhgjhg","jhghjg",999,1.5)
# T.append(9)
print(type(T))
T[2]= 'kshyd'
#Immutable

tup= (88,56,99,20,90,20)
print(type(tup))
print(tup[0])
print(len(tup))

tup1 = ()
#Its a valid but empty tuple

tup2 = (8,"Sadaf")
print(type(tup2))
#8 =(8)
tup3= (5,)
print(type(tup3))
#Orinal datatype

tup=(2,3,4,5,2)
tup.index(2)
tup.count(2)

#WAP  to ask the user to enter names of their 3 fav movies and store them in a list.
movies =[]
mov1= input("Enter your 1st movie")
movies.append(mov1)
mov2= input("Enter your 2nd movie")
movies.append(mov2)
mov3= input("Enter your 3rd movie")
movies.append(mov3)
print(movies)

#WAP to check if a list contains a palindrome of elements.
#[1,2,3,2,1]


#[1,'abc','abc'1]

#[1,2,3,4]
#Hint: Copy function, reverse, conditional statements

list1= [1,2,1]
copy_list1 = list1.copy()
copy_list1.reverse()
if copy_list1 == list1:
    print("Palindrome")
else:
    print("Not Palindrome")

gggg= {
"name":'Sadaf',
"marks":{
"science": 80,
"maths":90
},


"Age":25,
}
print(gggg)
print(gggg["name"])
print(gggg["Age"])

